import type { NextPage } from 'next'
import Head from 'next/head'
import CocktailList from '../components/CocktailList';
import { server } from '../config/index'

const Home: NextPage = ({ cocktails }: any) => {
  return (
    <div>
      <Head>
        <title>Cocktail Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CocktailList cocktails={cocktails} />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/cocktails`)
  const cocktails = await res.json()

  return {
    props: {
      cocktails
    }
  }
}

export default Home
