import type { NextPage } from 'next'
import Head from 'next/head'
import data from '../data.json'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Cocktail Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.map((d, i) => {
          return <p key={i}>{d.name}</p>
        })}
      </main>
    </div>
  )
}

export default Home
